### ISSUE TITLE
index out of bounds

### ISSUE THREAD

**Issue by cnaw** [chriswillott/jwst#15]
Hi Chris, 
I find that if I set  halofactorradius=3 the script crashes at the jumpsbigcutout[rr,cc]=4 step. The line number will not match the raw code because I included the checkifstar.py script in the code (and some imports). This is the step

                                #For jumps assume round and use all jump or saturated pixels to get area
                                numjumporsat = jumpsorsatcutout[np.where(jumpsorsatcutout>0)].size
                                radiusjumporsat = (numjumporsat/3.14159)**0.5             
                                radius = int(halofactorradius*radiusjumporsat)
                                rr, cc = disk((bigsizey/2-0.5,bigsizex/2-0.5), radius)
                                jumpsbigcutout[rr, cc] = 4

Running makewebbpsfmask nircam F115W 0.033 74 18 32
./temppsfmask_nircam_F115W_0p033_74.fits ./WebbPSF_nircam_F115W_0p033_74.fits
Traceback (most recent call last):
  File "/home/cnaw/python/commissioning/dosnowballflags_org.py", line 391, in <module>
    snowballflags(jumpdirfile,filtername,npixfind,satpixradius,halofactorradius,imagingmode)
  File "/home/cnaw/python/commissioning/dosnowballflags_org.py", line 308, in snowballflags
    jumpsbigcutout[rr, cc] = 4
IndexError: index 42 is out of bounds for axis 1 with size 42

Any clue why this happens ? I find a case where there is still a residual if I use the default parameters.

**Comment by jdavies-st** [comment]
A year late here, but I believe this is happening because the postage stamp of each object in the segmentation map is limited in size, currently ~3 times the object bounding box size.  So large radii in the halo factor will run out-of-bounds.

https://github.com/chriswillott/jwst/blob/c4f23f663885b4b0793c48ea33991c5f1eee9835/dosnowballflags.py#L141-L146

A solution might be to not make cut-outs at all and just use a temporary boolean array for each segmentation map object sized to the whole detector to allow larger increases of the halo radius.
